In [1]:
import numpy as np

# Array from List

In [4]:
l=[1,2,3,4,5]
a=np.array(l)

In [6]:
a # One dimensional array

array([1, 2, 3, 4, 5])

In [7]:
# Two dimensional array
b=np.array([[1,2,3],[4,5,6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

# Method For Numpy Array Creation

In [9]:
zero=np.zeros((3,4))  # 3 rows and 4 columns

In [11]:
zero # A 3x4 array consist of all zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
custom_array=np.full((2,3),10)  # 2 rows and 3 columns filled with ones,10 by default

In [14]:
custom_array

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
custom_array.shape # Shape of the array

(2, 3)

In [16]:
one_array=np.ones((2,3))  # 2 rows and 3 columns filled with ones

In [17]:
one_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
array=np.arange(10)  # Array with values ranging from 0 to 9

In [19]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
lin_array=np.linspace(0,5,10)  # Array with 10 values ranging from 0 to 5

In [21]:
lin_array

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
identy_array=np.eye(4)  # 4x4 Identity matrix

In [23]:
identy_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
empty_array=np.empty((2,3))  # 2 rows and 3 columns uninitialized

In [25]:
empty_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
id_array=np.identity(5)  # 5x5 Identity matrix

In [27]:
id_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])