In [1]:
import numpy as np

In [2]:
array_missing_value=np.array([1,2,np.nan,4,5,np.nan,7])
array_missing_value

array([ 1.,  2., nan,  4.,  5., nan,  7.])

In [3]:
np.isnan(array_missing_value)

array([False, False,  True, False, False,  True, False])

In [4]:
np.nan_to_num(array_missing_value, nan=0)

array([1., 2., 0., 4., 5., 0., 7.])

In [5]:
# check infinte values
array_with_inf=np.array([1,2,np.inf,4,-np.inf,6])
np.isinf(array_with_inf)

array([False, False,  True, False,  True, False])