In [1]:
import numpy as np

In [2]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# transpose change rows to columns and columns to rows
array.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
#Flattening the 2D array to 1D array
array.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Diemnsion of array
array.ndim

2

In [8]:
# size of array
array.size

9

In [9]:
# Total byte consumed by the elements of the array
array.nbytes

72

In [10]:
# indux with maximum value
array.argmax()

np.int64(8)

In [11]:
# indux with minimum value
array.argmin()

np.int64(0)

In [12]:
# sorted array indux
array.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])