In [1]:
import numpy as np

In [2]:
array=np.arange(10)  

In [3]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Access specific elements from array
array[2]  # Access the element at index 2

array([2, 3])

In [8]:
arr = np.array([[10, 20, 30, 40],
                    [50, 60, 70, 80],
                    [90, 100, 110, 120]])

In [12]:
# Access elements using indexing in 2D array
arr[1, 2]  # Access element at row index 1 and column index 2

np.int64(70)

In [13]:
# Access rows
arr[0]  # First row


array([10, 20, 30, 40])

In [14]:
# Access columns
arr[:, 1]  # Second column

array([ 20,  60, 100])

In [15]:
# Subarray sclicing
arr[0:2, 1:3]  # Subarray from rows 0-1 and columns 1-2

array([[20, 30],
       [60, 70]])