# 10 - Random Numbers & Simulation

NumPy's modern random API is **`np.random.default_rng()`** — a generator object you create once and reuse.

### Why a generator object?

```python
rng = np.random.default_rng(42)   # 42 = seed -> reproducible
rng.normal(size=(3, 3))           # same numbers every run
```

A **seed** makes randomness reproducible — essential for tests and teaching.

### Common distributions / methods

| Method | Produces |
|---|---|
| `rng.normal(mu, sigma, size)` | bell-shaped continuous values |
| `rng.uniform(lo, hi, size)` | flat random values |
| `rng.integers(lo, hi, size)` | random integers (hi exclusive) |
| `rng.binomial(n, p, size)` | number of successes |
| `rng.choice(a, size, p=...)` | pick elements, optionally with weights |
| `rng.permutation(a)` | shuffled copy |
| `rng.shuffle(a)` | shuffle in place |

### Simulation ideas

- **Random walk**: cumsum of random ±1 steps.
- **Monte Carlo π**: random points in a square, fraction inside a circle.

In [1]:
import numpy as np

rng = np.random.default_rng(42)   # seeded generator

## 1. Reproducibility

Two generators with the same seed produce identical sequences.

In [2]:
g1 = np.random.default_rng(1)
g2 = np.random.default_rng(1)
print(g1.integers(0, 100, 5))
print(g2.integers(0, 100, 5))

[47 51 75 95  3]
[47 51 75 95  3]


## 2. Distributions

Generate from common distributions and inspect their stats.

In [3]:
normal = rng.normal(loc=100, scale=10, size=10_000)
print("normal: mean", normal.mean().round(2), "std", normal.std().round(2))

normal: mean 99.9 std 10.06


In [4]:
uniform = rng.uniform(0, 1, size=10_000)
print("uniform: min", uniform.min().round(3), "max", uniform.max().round(3))

uniform: min 0.0 max 1.0


In [5]:
rolls = rng.integers(1, 7, size=12)   # dice rolls (1..6)
rolls

array([2, 2, 6, 4, 6, 3, 3, 6, 4, 6, 1, 4], dtype=int64)

In [6]:
flips = rng.binomial(n=10, p=0.5, size=20)   # heads in 10 coin flips, 20 trials
flips

array([6, 3, 3, 6, 6, 2, 4, 5, 3, 5, 5, 7, 4, 3, 1, 3, 6, 5, 4, 7],
      dtype=int64)

## 3. Sampling and shuffling

`choice` picks elements (with or without weights); `permutation`/`shuffle` reorder.

In [7]:
items = np.array(["apple", "banana", "cherry"])
rng.choice(items, size=6, p=[0.6, 0.3, 0.1])   # weighted sampling

array(['banana', 'apple', 'apple', 'banana', 'banana', 'cherry'],
      dtype='<U6')

In [8]:
deck = np.arange(52)
shuffled = rng.permutation(deck)   # shuffled copy
shuffled[:8]

array([30, 15,  1, 27, 35, 49, 18, 40])

In [9]:
rng.shuffle(deck)   # shuffles in place
deck[:8]

array([ 0, 48,  5, 49,  9, 12, 14, 46])

## 4. Random walk

Cumulative sum of random ±1 steps models a drunkard's walk / stock moves.

In [10]:
steps = rng.choice([-1, 1], size=100)
walk = np.cumsum(steps)
print("final position:", walk[-1])
print("max excursion  :", walk.max(), walk.min())
walk[:15]

final position: 6
max excursion  : 13 -1


array([1, 2, 3, 4, 3, 4, 5, 6, 5, 6, 5, 6, 7, 8, 9])

## 5. Monte Carlo estimation of pi

Throw random points into a unit square; the fraction landing in the quarter-circle approximates `pi / 4`.

In [11]:
n = 100_000
x = rng.uniform(0, 1, n)
y = rng.uniform(0, 1, n)
inside = (x**2 + y**2) <= 1
pi_est = 4 * inside.sum() / n
print(f"estimated pi: {pi_est:.4f}   (true pi: {np.pi:.4f})")

estimated pi: 3.1370   (true pi: 3.1416)


## 6. Bootstrapping a statistic

Resample with replacement many times to estimate the uncertainty of a mean.

In [12]:
sample = rng.normal(50, 5, size=200)
boot = np.array([rng.choice(sample, size=200, replace=True).mean() for _ in range(1000)])
print("sample mean      :", sample.mean().round(2))
print("bootstrap mean   :", boot.mean().round(2))
print("95% CI           :", np.percentile(boot, [2.5, 97.5]).round(2))

sample mean      : 50.05
bootstrap mean   : 50.05
95% CI           : [49.37 50.8 ]


## Summary

- Use `np.random.default_rng(seed)` for **reproducible** randomness.
- `normal`, `uniform`, `integers`, `binomial`, `choice`, `permutation`, `shuffle`.
- Power tools: random walks (`cumsum`), Monte Carlo, bootstrapping.

Next: **11-sorting-searching** — ordering and finding values fast.