# 04 - Mathematical Operations

NumPy makes maths on arrays **vectorised** — one expression replaces a whole Python loop.

### Element-wise arithmetic

`+`, `-`, `*`, `/`, `//`, `**` apply to **every element** at once (see 05-broadcasting for how shapes align).

### Universal functions (ufuncs)

`np.sqrt`, `np.exp`, `np.log`, `np.abs`, `np.sin`, ... run the same math on each element.

### Aggregations

| Function | Meaning |
|---|---|
| `np.sum` / `np.mean` | total / average |
| `np.min` / `np.max` | smallest / largest |
| `np.std` / `np.median` | spread / middle value |
| `np.argmin` / `np.argmax` | **index** of smallest / largest |
| `np.argsort` | index order for sorting |
| `np.count_nonzero` | how many non-zero values |

On 2D arrays add `axis=0` (down columns) or `axis=1` (across rows).

### Conditional selection

- `arr[condition]` → keep the matching **values** (boolean mask).
- `np.where(condition, a, b)` → element-wise `a` where true, `b` where false.

In [1]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

## 1. Arithmetic

Each operator works element by element.

In [2]:
array1 + array2   # addition

array([5, 7, 9])

In [3]:
array2 - array1   # subtraction

array([3, 3, 3])

In [4]:
array1 * array2   # multiplication

array([ 4, 10, 18])

In [5]:
array2 / array1   # division

array([4. , 2.5, 2. ])

In [6]:
array2 // array1  # floor division (integer quotient)

array([4, 2, 2])

In [7]:
array1 ** 2       # power

array([1, 4, 9])

## 2. Universal functions

Math functions applied to every element.

In [8]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081])

In [9]:
np.abs(np.array([-1, 2, -3]))

array([1, 2, 3])

In [10]:
np.exp(array1).round(3)

array([ 2.718,  7.389, 20.086])

## 3. Aggregations

Reduce the whole array to a single number.

In [11]:
print("sum   :", np.sum(array1))
print("mean  :", np.mean(array1))
print("min   :", np.min(array1))
print("max   :", np.max(array1))
print("std   :", np.std(array1))
print("median:", np.median(array1))

sum   : 6
mean  : 2.0
min   : 1
max   : 3
std   : 0.816496580927726
median: 2.0


## 4. Aggregations with `axis`

On a 2D array, `axis=0` goes down columns, `axis=1` goes across rows.

In [12]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print("column sums (axis=0):", m.sum(axis=0))
print("row sums    (axis=1):", m.sum(axis=1))

column sums (axis=0): [5 7 9]
row sums    (axis=1): [ 6 15]


## 5. Positions of extremes

`argmin` / `argmax` return the **index** of the smallest / largest value.

In [13]:
arr = np.array([4, 1, 9, 2])
print("array        :", arr)
print("argmin (idx) :", arr.argmin())
print("argmax (idx) :", arr.argmax())

array        : [4 1 9 2]
argmin (idx) : 1
argmax (idx) : 2


## 6. Sorting

`np.sort` returns sorted values; `argsort` returns the index order that would sort the array.

In [14]:
np.sort(arr)

array([1, 2, 4, 9])

In [15]:
np.argsort(arr)   # indexes that put the array in order

array([1, 3, 0, 2], dtype=int64)

## 7. Conditional selection

Two ways to pick values based on a condition.

In [16]:
# Boolean mask: keep only values greater than 2
array1[array1 > 2]

array([3])

In [17]:
# np.where: choose values element by element (keep value, or 0)
np.where(array1 > 2, array1, 0)

array([0, 0, 3])

In [18]:
np.count_nonzero(array1)   # how many non-zero values

3

## Summary

- Arithmetic and ufuncs (`sqrt`, `abs`, `exp`) are **element-wise and vectorised**.
- Aggregations: `sum`, `mean`, `min`, `max`, `std`, `median` (+ `axis=` on 2D).
- `argmin`/`argmax`/`argsort` give positions; masks and `np.where` select by condition.

Next: **05-broadcasting** — how NumPy aligns different shapes.