# 01 - NumPy Basics

## What is NumPy?

**NumPy** (Numerical Python) is the foundation of scientific computing in Python. Its core object is the **`ndarray`** — a fast, fixed-size, multidimensional array.

### Why arrays instead of lists?

| | Python list | NumPy `ndarray` |
|---|---|---|
| Stores | mixed types allowed | one **dtype** for all elements |
| Element access | loop needed | **vectorised** (C speed) |
| Memory | scattered objects | **contiguous** block |
| Maths on whole list | error / slow loop | `a * 2` just works |

### Creating arrays

| Function | Creates |
|---|---|
| `np.array(list)` | array from Python data |
| `np.zeros(shape)` | all zeros |
| `np.ones(shape)` | all ones |
| `np.full(shape, v)` | all equal to `v` |
| `np.arange(n)` | 0, 1, 2, ... n-1 |
| `np.linspace(a, b, n)` | `n` evenly spaced values between `a` and `b` |
| `np.eye(n)` | `n x n` identity matrix |
| `np.random.default_rng()` | arrays of random numbers |

### Key attributes

`shape` (dimensions), `ndim` (number of dims), `dtype` (element type), `size` (total elements), `nbytes` (memory).

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 1.26.4


## 1. From list to array

A **1D array** from a Python list, then a **2D array** from a list of lists (rows).

In [2]:
l = [1, 2, 3, 4, 5]
a = np.array(l)
a

array([1, 2, 3, 4, 5])

In [3]:
# Two dimensional array: a list of rows
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

## 2. Pre-filled arrays

Fast ways to build arrays without typing data.

In [4]:
zero = np.zeros((3, 4))   # 3 rows, 4 columns, all zeros
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
one = np.ones((2, 3))     # 2 rows, 3 columns, all ones
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
filled = np.full((2, 3), 10)  # all values equal to 10
filled

array([[10, 10, 10],
       [10, 10, 10]])

In [7]:
empty = np.empty((2, 3))   # uninitialised (fast, but values are garbage)
empty

array([[1., 1., 1.],
       [1., 1., 1.]])

## 3. Ranges of values

`arange` gives consecutive integers; `linspace` gives evenly spaced values over a range.

In [8]:
arr = np.arange(10)        # 0 to 9
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
lin = np.linspace(0, 5, 10)  # 10 values evenly spaced from 0 to 5
lin

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## 4. Identity and random arrays

`eye` / `identity` build identity matrices; `default_rng` is the modern way to get random values.

In [10]:
eye = np.eye(4)            # 4x4 identity matrix
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
ident = np.identity(5)     # 5x5 identity matrix
ident

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
rng = np.random.default_rng(42)          # reproducible generator
rnd = rng.normal(size=(3, 3))            # 3x3 random normal values
rnd

array([[ 0.30471708, -1.03998411,  0.7504512 ],
       [ 0.94056472, -1.95103519, -1.30217951],
       [ 0.1278404 , -0.31624259, -0.01680116]])

## 5. Array attributes

Ask the array about itself: shape, dimension count, dtype, size and memory.

In [13]:
custom = np.full((2, 3), 10)
print("shape :", custom.shape)
print("ndim  :", custom.ndim)
print("dtype :", custom.dtype)
print("size  :", custom.size)
print("nbytes:", custom.nbytes)

shape : (2, 3)
ndim  : 2
dtype : int32
size  : 6
nbytes: 24


In [14]:
# Change the element type
ints = np.array([1, 2, 3])
floats = ints.astype("float64")
print(ints.dtype, "->", floats.dtype)

int32 -> float64


## Summary

- NumPy arrays (`ndarray`) are **fast, vectorised, single-dtype** containers.
- Create them with `np.array`, `zeros`, `ones`, `full`, `arange`, `linspace`, `eye`, `default_rng`.
- Inspect them with `shape`, `ndim`, `dtype`, `size`, `nbytes`; change type with `.astype()`.

Next: **02-indexing-slicing** — reading elements and sub-arrays.