# 03 - Array Manipulation


Reshaping and combining arrays is how you prepare data for a computation.

| Operation | Function / method | Result |
|---|---|---|
| Reshape | `a.reshape((r, c))` | same data, new shape |
| Flatten | `a.ravel()` / `a.flatten()` | 1D array |
| Transpose | `a.T` | rows <-> columns |
| Concatenate | `np.concatenate([a, b])` | join arrays |
| Stack rows | `np.vstack([a, b])` | one under the other |
| Stack columns | `np.hstack([a, b])` | side by side |
| Reverse | `np.flip(a)` | elements in reverse order |
| Split | `np.array_split(a, n)` | divide into parts |

### `ravel` vs `flatten`

- `ravel()` returns a **view** when possible (fast, shares memory).
- `flatten()` always returns a **copy**.

### Reshape trick
You can let NumPy compute a dimension for you with `-1`: `a.reshape(2, -1)` fits the rest automatically (total size must match).

In [1]:
import numpy as np

array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1. Reshaping

`reshape((2, 5))` reinterprets the same 10 values as 2 rows of 5.

In [2]:
new_array = array.reshape((2, 5))
new_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
# Let NumPy work out one dimension with -1
array.reshape(5, -1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 2. Back to 1D

`ravel()` and `flatten()` both turn the array back into one dimension.

In [4]:
new_array.ravel()   # or new_array.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
new_array.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Transposing

`a.T` swaps rows and columns.

In [6]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("original shape:", mat.shape)
print("transposed shape:", mat.T.shape)
mat.T

original shape: (2, 3)
transposed shape: (3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

## 4. Combining arrays

`concatenate` joins 1D arrays end-to-end.

In [7]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.concatenate((a1, a2))

array([1, 2, 3, 4, 5, 6])

## 5. Stacking 2D arrays

`vstack` stacks **vertically** (rows); `hstack` stacks **horizontally** (columns).

In [8]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[7, 8, 9], [10, 11, 12]])

In [9]:
np.vstack((m1, m2))   # one under the other

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
np.hstack((m1, m2))   # side by side

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## 6. Reversing and splitting

`np.flip` reverses an array (it is a function, not a method).

In [11]:
np.flip(a1)          # reversed

array([3, 2, 1])

In [12]:
np.array_split(a1, 3)  # split into 3 parts

[array([1]), array([2]), array([3])]

## 7. Related attributes

A quick recap of the array's own numbers.

In [13]:
print("ndim   :", mat.ndim)      # number of dimensions
print("size   :", mat.size)      # total elements
print("nbytes :", mat.nbytes)    # memory used

ndim   : 2
size   : 6
nbytes : 24


## Summary

- `reshape((r, c))` (with `-1` magic), `ravel()`/`flatten()` for 1D, `a.T` to transpose.
- Combine with `concatenate`, `vstack`, `hstack`; reverse with `np.flip`.
- Note: `flip` and `flatten` are **functions/methods with specific names** — `np.flip` is the function form.

Next: **04-math-operations** — arithmetic and aggregations.