# 06 - Handling Missing Values


Real data contains **missing** (`NaN`) and **infinite** (`Inf`) values. NumPy gives you tools to detect and fix them.

| Function | Returns `True` when the value is... |
|---|---|
| `np.isnan(x)` | Not a Number (`NaN`) |
| `np.isinf(x)` | positive or negative infinity |
| `np.isfinite(x)` | **finite** (not NaN and not Inf) |
| `np.nan_to_num(x)` | replaces NaN → 0, Inf → large finite numbers |

### Key gotcha

`NaN == NaN` is `False` — you **cannot** compare with `==` to find missing values. You must use `np.isnan` (or a mask).

### Strategies

1. **Detect** — `np.isnan`, `np.isinf`.
2. **Remove** — keep only finite values with `arr[np.isfinite(arr)]`.
3. **Replace** — `np.nan_to_num`, or fill with a statistic (mean, median...).
4. **Aggregate safely** — `np.nanmean`, `np.nansum`, `np.nanstd` skip the missing values instead of returning `NaN`.

In [1]:
import numpy as np

arr = np.array([1, 2, np.nan, 4, 5, np.nan, 7])
arr

array([ 1.,  2., nan,  4.,  5., nan,  7.])

## 1. Detecting missing values

`np.isnan` builds a boolean mask of where the missing values are.

In [2]:
np.isnan(arr)

array([False, False,  True, False, False,  True, False])

In [3]:
# Why not ==? Because NaN never equals itself
print("NaN == NaN is", np.nan == np.nan)
print("np.isnan(np.nan) is", np.isnan(np.nan))

NaN == NaN is False
np.isnan(np.nan) is True


## 2. Replacing with `nan_to_num`

`nan_to_num` turns `NaN` into 0 (and infinities into large finite numbers).

In [4]:
np.nan_to_num(arr)

array([1., 2., 0., 4., 5., 0., 7.])

## 3. Filtering out missing values

Use `~` (NOT) on the mask to keep only the valid values.

In [5]:
clean = arr[~np.isnan(arr)]
clean

array([1., 2., 4., 5., 7.])

## 4. Infinity

`isinf` and `isfinite` deal with `Inf` values.

In [6]:
with_inf = np.array([1, 2, np.inf, 4, -np.inf, 6])
np.isinf(with_inf)

array([False, False,  True, False,  True, False])

In [7]:
np.isfinite(with_inf)   # True only for normal numbers

array([ True,  True, False,  True, False,  True])

In [8]:
# Remove both NaN and Inf in one go
dirty = np.array([1.0, np.nan, 2.0, np.inf, 3.0])
dirty[np.isfinite(dirty)]

array([1., 2., 3.])

## 5. Safe aggregations

Ordinary `mean` returns `NaN` when data contains missing values; the `nan`-variants skip them.

In [9]:
print("mean  (ignores nothing):", np.mean(arr))
print("nanmean (skips NaN)    :", np.nanmean(arr).round(3))
print("nansum (skips NaN)     :", np.nansum(arr))
print("nanstd (skips NaN)     :", np.nanstd(arr).round(3))

mean  (ignores nothing): nan
nanmean (skips NaN)    : 3.8
nansum (skips NaN)     : 19.0
nanstd (skips NaN)     : 2.135


## 6. Filling with a statistic

Replace missing values with the mean of the valid ones.

In [10]:
filled = np.where(np.isnan(arr), np.nanmean(arr), arr)
filled

array([1. , 2. , 3.8, 4. , 5. , 3.8, 7. ])

In [11]:
# Verify: no NaN left
np.isnan(filled).sum()

0

## Summary

Want to go deeper? Continue to the **advanced tier** (07–15): **07-fancy-indexing** → **08-linear-algebra** → **09-universal-functions** → **10-random-numbers** → **11-sorting-searching** → **12-structured-arrays** → **13-file-io** → **14-performance** → **15-analysis-workflow**.

- Detect with `np.isnan` / `np.isinf` / `np.isfinite` — **never** `==` against NaN.
- Remove with a mask (`arr[~np.isnan(arr)]`) or replace with `np.nan_to_num` / `np.where`.
- Use `np.nanmean` / `np.nansum` / `np.nanstd` for safe aggregations.

That completes the **core** NumPy journey: **create → shape → select → transform → compute → clean**.