# 11 - Sorting & Searching

NumPy provides fast, vectorised order and lookup operations.

### Sorting

| Function | Returns |
|---|---|
| `np.sort(a)` | sorted **copy** |
| `a.sort()` | sorts **in place** (method) |
| `np.argsort(a)` | index order that sorts `a` |
| `np.partition(a, k)` | elements around the `k`-th position (partial sort, faster) |
| `np.argpartition(a, k)` | indices for `np.partition` |

On 2D arrays use `axis=0` / `axis=1`.

### Searching

| Function | Finds |
|---|---|
| `np.searchsorted(a, v)` | where `v` fits into a sorted `a` |
| `np.argmin` / `np.argmax` | index of min / max |
| `np.where(cond)` | indices where `cond` is true |
| `np.nonzero(a)` | indices of non-zero elements |

### Unique & counting

- `np.unique(a, return_counts=True)` — distinct values + counts.
- `np.bincount(a)` — fast counts for non-negative integers (acts like a histogram).
- `np.in1d(a, b)` — which elements of `a` are in `b`.

In [1]:
import numpy as np

a = np.array([3, 1, 4, 1, 5, 9, 2, 6])
a

array([3, 1, 4, 1, 5, 9, 2, 6])

## 1. Sorting

`np.sort` returns a sorted copy; the method `a.sort()` sorts in place.

In [2]:
np.sort(a)

array([1, 1, 2, 3, 4, 5, 6, 9])

In [3]:
np.sort(a)[::-1]   # descending

array([9, 6, 5, 4, 3, 2, 1, 1])

In [4]:
print("original untouched:", a)

original untouched: [3 1 4 1 5 9 2 6]


## 2. `argsort` — sort by another array

`argsort` gives the index order, so you can sort **related arrays together**.

In [5]:
names = np.array(["c", "a", "b"])
values = np.array([30, 10, 20])
order = np.argsort(values)
print("order :", order)
print("names :", names[order])
print("values:", values[order])

order : [1 2 0]
names : ['a' 'b' 'c']
values: [10 20 30]


## 3. Sorting 2D arrays

Choose the axis: rows or columns.

In [6]:
m = np.array([[5, 2], [1, 9], [7, 3]])
np.sort(m, axis=0)   # sort down each column

array([[1, 2],
       [5, 3],
       [7, 9]])

In [7]:
np.sort(m, axis=1)   # sort across each row

array([[2, 5],
       [1, 9],
       [3, 7]])

## 4. Partitioning — faster than full sort

`np.partition` guarantees the `k`-th element is in its sorted position; elements before it are all smaller, after it all larger — but not ordered internally.

In [8]:
# The 3rd smallest element is at index 3; smaller ones before, larger after
np.partition(a, 3)

array([1, 1, 2, 3, 5, 9, 4, 6])

In [9]:
# 3 largest values via argpartition
idx = np.argpartition(a, -3)[-3:]
np.sort(a[idx])

array([5, 6, 9])

## 5. Searching

`where` / `nonzero` give the positions of matching elements.

In [10]:
np.where(a > 4)

(array([4, 5, 7], dtype=int64),)

In [11]:
np.nonzero(np.array([0, 5, 0, 7]))

(array([1, 3], dtype=int64),)

In [12]:
# Insertion positions in sorted data
np.searchsorted(np.sort(a), [4, 10])

array([4, 8], dtype=int64)

## 6. Unique values and counting

`unique` with counts is a one-line histogram; `bincount` is the fast integer counter.

In [13]:
vals, counts = np.unique(a, return_counts=True)
print("values:", vals)
print("counts:", counts)

values: [1 2 3 4 5 6 9]
counts: [2 1 1 1 1 1 1]


In [14]:
np.bincount(np.array([0, 3, 1, 3, 0, 3]))

array([2, 1, 0, 3], dtype=int64)

In [15]:
np.in1d(a, [2, 9])   # which elements of a are in [2, 9]

array([False, False, False, False, False,  True,  True, False])

## Summary

- `np.sort` / `a.sort()` / `argsort` (sort by another array) / `partition` (faster partial sort).
- `where`, `nonzero`, `searchsorted`, `argmin`/`argmax` for searching.
- `np.unique(..., return_counts=True)` and `np.bincount` for counting.

Next: **12-structured-arrays** — tables inside an array.