# 08 - Linear Algebra


NumPy's `np.linalg` module brings fast **linear algebra** to Python.

### Matrix multiplication

| Form | What |
|---|---|
| `a * b` | element-wise (see 05-broadcasting) |
| `a @ b` / `np.matmul(a, b)` | **true matrix product** |
| `np.dot(a, b)` | dot product (matmul for 2D) |
| `np.inner` / `np.outer` | vector inner / outer product |

For matrices `(n,k) @ (k,m) -> (n,m)`. The `@` operator is the modern, readable way.

### Common `np.linalg` functions

| Function | Meaning |
|---|---|
| `det` | determinant (0 -> singular) |
| `inv` | inverse matrix |
| `solve(A, b)` | solve `A x = b` (faster & more stable than `inv @ b`) |
| `eig` | eigenvalues & eigenvectors |
| `norm` | vector / matrix magnitude |
| `trace` | sum of diagonal elements |
| `matrix_power` | integer powers of a matrix |

> **Rule:** prefer `np.linalg.solve` over `np.linalg.inv` when solving systems — it is numerically stable and faster.

In [1]:
import numpy as np

A = np.array([[2.0, 1.0],
              [1.0, 3.0]])
B = np.array([[1.0, 2.0],
              [3.0, 4.0]])
v = np.array([1.0, 2.0])

## 1. Element-wise vs matrix multiplication

`*` multiplies element by element; `@` does the real matrix product.

In [2]:
A * B     # element-wise

array([[ 2.,  2.],
       [ 3., 12.]])

In [3]:
A @ B     # matrix product

array([[ 5.,  8.],
       [10., 14.]])

In [4]:
A @ v     # matrix-vector product

array([4., 7.])

## 2. Dot, inner, outer

`dot` is the classic product; `outer` builds a matrix from two vectors.

In [5]:
np.dot(v, v)        # scalar dot product

5.0

In [6]:
np.outer(v, v)      # 2x2 outer product matrix

array([[1., 2.],
       [2., 4.]])

## 3. Determinant and inverse

`det` tells whether a matrix is invertible; `inv` returns the inverse.

In [7]:
np.linalg.det(A)

5.000000000000001

In [8]:
A_inv = np.linalg.inv(A)
print("inverse:")
A_inv
print("A @ A_inv (should be identity):")
np.round(A @ A_inv, 2)

inverse:
A @ A_inv (should be identity):


array([[ 1.,  0.],
       [-0.,  1.]])

## 4. Solving linear systems

Solve `A x = b` for `x` with `np.linalg.solve`.

In [9]:
b = np.array([5.0, 7.0])
x = np.linalg.solve(A, b)
print("solution x:", x)
print("check A @ x:", np.round(A @ x, 2))   # should equal b

solution x: [1.6 1.8]
check A @ x: [5. 7.]


## 5. Eigenvalues and eigenvectors

`eig` returns `(eigenvalues, eigenvectors)`. Each column of the vectors matrix is an eigenvector.

In [10]:
w, vec = np.linalg.eig(A)
print("eigenvalues :", np.round(w, 3))
print("eigenvectors:")
np.round(vec, 3)

eigenvalues : [1.382 3.618]
eigenvectors:


array([[-0.851, -0.526],
       [ 0.526, -0.851]])

## 6. Norms and trace

`norm` measures size; `trace` sums the diagonal.

In [11]:
print("L2 norm of v      :", np.linalg.norm(v).round(4))
print("L1 norm of v      :", np.linalg.norm(v, ord=1))
print("Frobenius norm of A:", np.linalg.norm(A).round(4))
print("trace of A        :", np.trace(A))

L2 norm of v      : 2.2361
L1 norm of v      : 3.0
Frobenius norm of A: 3.873
trace of A        : 5.0


## 7. Matrix powers

`matrix_power` raises a square matrix to an integer power (e.g. Markov chains).

In [12]:
np.linalg.matrix_power(B, 2)   # B @ B

array([[ 7., 10.],
       [15., 22.]])

## Summary

- `*` = element-wise; `@` / `np.matmul` = matrix product; `np.dot`, `np.inner`, `np.outer` for vector products.
- `np.linalg`: `det`, `inv`, `solve`, `eig`, `norm`, `matrix_power`.
- Prefer `solve(A, b)` over `inv(A) @ b`.

Next: **09-universal-functions** — NumPy's function engine.