# 09 - Universal Functions (ufuncs)


A **ufunc** is a function that operates element-wise on arrays (`np.add`, `np.multiply`, `np.sqrt`, ...). They are the engine behind most vectorised NumPy code.

### Methods every ufunc carries

| Method | Example | Result |
|---|---|---|
| `reduce` | `np.add.reduce(a)` | one value (like `np.sum`) |
| `accumulate` | `np.add.accumulate(a)` | running totals (like `np.cumsum`) |
| `outer` | `np.multiply.outer(a, b)` | 2D table of all pairs |
| `reduceat` | `np.add.reduceat(a, idx)` | reductions over segments |

### Parameters of every ufunc

| Parameter | Effect |
|---|---|
| `out` | write results into an existing array |
| `where` | only compute where the mask is `True` |
| `dtype` | force the result type |
| `axis` | apply a reduction along an axis |

### Making your own ufunc

- `np.vectorize(func)` — wraps a Python function (convenient but **not** faster than a loop).
- `np.frompyfunc(func, nin, nout)` — creates a real ufunc.

> For pure-Python logic with no `np.*` calls, vectorisation is still better done with broadcasting/masks.

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

## 1. `reduce`

Combine all elements with the ufunc's operation.

In [2]:
np.add.reduce(a)          # 1+2+3+4

10

In [3]:
np.multiply.reduce(a)     # 1*2*3*4

24

In [4]:
# reduce along an axis on a 2D array
m = np.array([[1, 2], [3, 4]])
np.add.reduce(m, axis=1)  # row sums

array([3, 7])

## 2. `accumulate`

Running result at every step (cumulative sums/product).

In [5]:
np.add.accumulate(a)      # [1, 1+2, 1+2+3, ...]

array([ 1,  3,  6, 10])

In [6]:
np.maximum.accumulate(np.array([3, 1, 4, 1, 5]))   # running max

array([3, 3, 4, 4, 5])

## 3. `outer`

Apply the operation to **every pair** of elements — a fast way to build grids/tables.

In [7]:
np.add.outer(np.array([1, 2]), np.array([10, 20, 30]))

array([[11, 21, 31],
       [12, 22, 32]])

In [8]:
np.greater.outer(np.array([1, 3]), np.array([2, 2, 4]))   # comparison table

array([[False, False, False],
       [ True,  True, False]])

## 5. `out`, `where`, `dtype` parameters

Control where results land and which elements are computed.

In [10]:
# Write into an existing buffer with out=
buffer = np.zeros_like(a)
np.multiply(a, b, out=buffer)
buffer

array([ 10,  40,  90, 160])

In [11]:
# Only compute where the mask is True (others left as-is)
np.add(a, b, where=np.array([True, False, True, False]))

array([11, 20, 33, 10])

In [12]:
# Force integer division result dtype
np.divide(a, b, dtype=float).round(3)

array([0.1, 0.1, 0.1, 0.1])

## 6. Building custom functions

`np.vectorize` and `np.frompyfunc` wrap Python logic into array-callable form.

In [13]:
def grade(x):
    return "pass" if x >= 60 else "fail"

vec_grade = np.vectorize(grade)
vec_grade(np.array([45, 90, 61]))

array(['fail', 'pass', 'pass'], dtype='<U4')

In [14]:
def clip_ratio(x, y):
    return x / y if y != 0 else 0.0

safe_div = np.frompyfunc(clip_ratio, 2, 1)
safe_div(np.array([10, 20]), np.array([2, 0]))

array([5.0, 0.0], dtype=object)

## Summary

- Ufuncs carry `reduce`, `accumulate`, `outer`, `reduceat` methods.
- Control them with `out`, `where`, `dtype`, `axis`.
- Wrap Python logic with `np.vectorize` / `np.frompyfunc` (still prefer masks/broadcast for speed).

Next: **10-random-numbers** — generators, distributions, and simulations.