# 02 - Indexing & Slicing

**Indexing** reads a single element; **slicing** reads a sub-array. Both use square brackets `[...]`.

### 1D indexing
```python
a[2]     # third element
a[-1]    # last element (negative = count from the end)
```

### 2D indexing
```python
arr[1, 2]     # row 1, column 2
arr[0]        # whole first row
arr[:, 1]     # whole second column (':' = all)
```

### Slicing syntax `start : stop : step`
```python
a[0:5]     # positions 0..4
a[::2]     # every second element
arr[0:2, 1:3]  # rows 0-1, columns 1-2 (a sub-array)
```

### Boolean (mask) indexing
A condition produces a `True/False` mask; `arr[mask]` keeps only the `True` positions:
```python
arr[arr > 5]
```

### Views vs copies
Slices return **views** (no new data is copied — modifying them changes the original!). Use `.copy()` when you want an independent array.

In [1]:
import numpy as np

array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1. Indexing a 1D array

Positive indices start at 0; negative indices count from the end.

In [2]:
array[2]    # element at index 2

2

In [3]:
array[-1]   # last element
array[-3]   # third from the end

7

## 2. Slicing a 1D array

`start : stop : step` — stop is exclusive, like Python strings/lists.

In [4]:
array[2:7]   # positions 2 to 6

array([2, 3, 4, 5, 6])

In [5]:
array[::2]   # every second element

array([0, 2, 4, 6, 8])

In [6]:
array[::-1]  # reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 3. Indexing a 2D array

Rows first, then columns: `arr[row, col]`.

In [7]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [8]:
arr[1, 2]   # row index 1, column index 2

70

In [9]:
arr[0]      # first row

array([10, 20, 30, 40])

In [10]:
arr[:, 1]   # second column (all rows, column 1)

array([ 20,  60, 100])

## 4. Slicing a 2D array

Slice rows and columns together to grab a **sub-array**.

In [11]:
arr[0:2, 1:3]   # rows 0-1 and columns 1-2

array([[20, 30],
       [60, 70]])

In [12]:
arr[::2]        # every second row

array([[ 10,  20,  30,  40],
       [ 90, 100, 110, 120]])

## 5. Boolean (mask) indexing

Keep only the elements that satisfy a condition.

In [13]:
# Show the mask first
arr > 50

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [14]:
# Keep only values greater than 50
arr[arr > 50]

array([ 60,  70,  80,  90, 100, 110, 120])

## 6. Views vs copies

Slices are **views**: changing them changes the original. `.copy()` breaks the link.

In [15]:
view = arr[:2]
view[0, 0] = 999
print("view changed -> original also changed:")
arr

view changed -> original also changed:


array([[999,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [16]:
# A real copy is independent
copy = arr.copy()
copy[0, 0] = -1
print("copy changed -> original untouched:")
arr

copy changed -> original untouched:


array([[999,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

## Summary

- 1D: `a[i]`, `a[-1]`; slices `a[start:stop:step]`.
- 2D: `arr[row, col]`, `arr[0]` (row), `arr[:, 1]` (column), `arr[0:2, 1:3]` (sub-array).
- Masks: `arr[arr > 50]` keeps matching values.
- Slices are **views**; use `.copy()` for an independent array.

Next: **03-array-manipulation** — reshaping and combining arrays.